### ISSUE TITLE
Decoding Problems

### ISSUE THREAD

**Issue by yanrs17** [phipsgabler/trello2md#5]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 3462: illegal
 multibyte sequence

**Comment by phipsgabler** [comment]
Hi,

can you provide details on when this error occurs? 

Are you perhaps using Windows with some CJK language settings, but were trying to process a UTF-8 file containing some multibyte characters? Because as far as I have understood it, `open` uses as default encoding whatever `locale.getpreferredencoding()` returns. On my Ubuntu machine, using, e.g., Chinese characters in UTF-8 works without your patch, since UTF-8 is the default.

And if that's the case, I'd preferably have a command-line option to pass the encoding to be used, rather than using UTF-8 as default. Or maybe default to it, but still provide the option to change.

**Comment by phipsgabler** [comment]
Should be fixed after merging #6. I chaged the implementation to an option, as described above.
